window.websiteContent = {
  apiBaseUrl: 'http://localhost:5002/api',
  contact: {
    email: 'sales@lekha.app',
    supportEmail: 'support@lekha.app',
    phone: '+91 9538301004',
    address: 'Athani, Karnataka, India',
  },
  heroStats: [
    { label: 'Complete bill in 2 steps', value: '2-step' },
    { label: 'GST bills, inventory, dues', value: 'All-in-one' },
    { label: 'Multi-device, users, shops', value: 'Scale ready' },
  ],
  comparisons: [
    {
      title: 'What many billing apps provide',
      tone: 'muted',
      items: [
        'Basic invoice creation',
        'Simple product list',
        'Single-device usage',
        'Minimal reporting',
        'Limited due follow-up',
      ],
    },
    {
      title: 'What Lekha provides',
      tone: 'accent',
      items: [
        'Create GST bills online and share with customers',
        'GST filing made simpler and faster',
        'Send payment reminders to recover dues',
        'Customer credits with full history',
        'Multi-device, multi-user, multi-shop operations',
        'Return orders and stock adjustment flow',
        'Business dashboard, cash flow tracking, financial reports',
      ],
    },
  ],
  visualFeatures: [
    {
      title: 'GST billing that feels instant',
      description: 'Create GST bills online, finish checkout in 2 steps, and share invoices with customers quickly.',
      image: './assets/gst-billing-share.svg',
      chips: ['GST Bills', 'Share Instantly', '2-Step Billing'],
    },
    {
      title: 'Recover dues with reminders',
      description: 'Send payment reminders, track customer credits, and keep every collection linked to history.',
      image: './assets/dues-reminders.svg',
      chips: ['Payment Reminders', 'Customer Credit', 'History'],
    },
    {
      title: 'Inventory without confusion',
      description: 'Manage small business inventory seamlessly with low-stock visibility and product-level tracking.',
      image: './assets/inventory-alerts.svg',
      chips: ['Inventory', 'Low Stock Alert', 'Product Control'],
    },
    {
      title: 'One system across shops and devices',
      description: 'Work across multiple devices, multiple users, and multiple shops with clean access control.',
      image: './assets/control-showcase.svg',
      chips: ['Multi-Device', 'Multi-User', 'Multi-Shop'],
    },
    {
      title: 'Returns, payments, and transaction messaging',
      description: 'Handle return orders, multi-payment options, and transaction messaging from the same workflow.',
      image: './assets/reports-payments.svg',
      chips: ['Returns', 'Multi-Payment', 'Messaging'],
    },
    {
      title: 'Dashboard and reports that guide action',
      description: 'See business dashboard metrics, cash flow tracking, and financial reports without digging through clutter.',
      image: './assets/hero-dashboard.svg',
      chips: ['Dashboard', 'Cash Flow', 'Financial Reports'],
    },
  ],
  modules: [
    'Business Dashboard',
    'GST Billing',
    'Inventory Management',
    'Low Stock Alert',
    'Customer Credits',
    'Payment Reminders',
    'Return Orders',
    'Financial Reports',
    'Transaction Messaging',
    'Multi-Payment Option',
    'Multi-Shop Control',
    'Multi-User Access',
  ],
  pricingPlans: [
    {
      name: 'Starter',
      price: '699',
      cadence: '/month',
      note: 'Billed annually',
      description: 'A clean GST billing setup for one retail counter.',
      cta: 'Request Starter Demo',
      highlight: false,
      features: [
        '1 shop',
        'Up to 2 users',
        'Unlimited GST bills',
        'Inventory tracking',
        'Basic reports',
      ],
    },
    {
      name: 'Growth',
      price: '1,499',
      cadence: '/month',
      note: 'Billed annually',
      description: 'For teams that want dues, users, and better daily visibility.',
      cta: 'Book Growth Demo',
      highlight: true,
      features: [
        'Up to 3 shops',
        'Up to 8 users',
        'Customer credit and reminders',
        'Role-based access',
        'Branch-wise visibility',
      ],
    },
    {
      name: 'Scale',
      price: '2,999',
      cadence: '/month',
      note: 'Billed annually',
      description: 'For growing retail groups that need strong multi-branch control.',
      cta: 'Talk to Sales',
      highlight: false,
      features: [
        'Up to 10 shops',
        'Up to 25 users',
        'Advanced financial reports',
        'Centralized monitoring',
        'Priority support',
      ],
    },
  ],
  comparisonNote:
    'Plans are built for Indian retail businesses that want GST billing, stock visibility, and due collections in one modern workflow.',
};
